name: sistema_de_gestion_academica
description: Sistema de Gestión Académica con seguimiento curricular para la carrera de Ingeniería Civil Informática Advance de la UNAB

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Persistencia de datos local
  shared_preferences: ^2.5.3
  
  # Información de la app (versión, nombre, etc)
  package_info_plus: ^9.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# Configuración para generar íconos de la app
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#8B0088"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  min_sdk_android: 21








